import type { Metadata } from "next";
import { Goldman } from "next/font/google";
import "../globals.css";
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/all'
import { useGSAP } from '@gsap/react'
import 'leaflet/dist/leaflet.css';

const inter = Goldman({ subsets: ["latin"] , weight:['400']});

export const metadata: Metadata = {
  title: "Home | Europe Professional Training",
  description: "Generated by create next app",
};

gsap.registerPlugin(ScrollTrigger)
gsap.registerPlugin(useGSAP);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} > 
        {children}
      </body>
    </html>
  );
}
